require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe InternalMessagesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # InternalMessage. As you add validations to InternalMessage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InternalMessagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all internal_messages as @internal_messages" do
      internal_message = InternalMessage.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:internal_messages)).to eq([internal_message])
    end
  end

  describe "GET show" do
    it "assigns the requested internal_message as @internal_message" do
      internal_message = InternalMessage.create! valid_attributes
      get :show, {:id => internal_message.to_param}, valid_session
      expect(assigns(:internal_message)).to eq(internal_message)
    end
  end

  describe "GET new" do
    it "assigns a new internal_message as @internal_message" do
      get :new, {}, valid_session
      expect(assigns(:internal_message)).to be_a_new(InternalMessage)
    end
  end

  describe "GET edit" do
    it "assigns the requested internal_message as @internal_message" do
      internal_message = InternalMessage.create! valid_attributes
      get :edit, {:id => internal_message.to_param}, valid_session
      expect(assigns(:internal_message)).to eq(internal_message)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InternalMessage" do
        expect {
          post :create, {:internal_message => valid_attributes}, valid_session
        }.to change(InternalMessage, :count).by(1)
      end

      it "assigns a newly created internal_message as @internal_message" do
        post :create, {:internal_message => valid_attributes}, valid_session
        expect(assigns(:internal_message)).to be_a(InternalMessage)
        expect(assigns(:internal_message)).to be_persisted
      end

      it "redirects to the created internal_message" do
        post :create, {:internal_message => valid_attributes}, valid_session
        expect(response).to redirect_to(InternalMessage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved internal_message as @internal_message" do
        post :create, {:internal_message => invalid_attributes}, valid_session
        expect(assigns(:internal_message)).to be_a_new(InternalMessage)
      end

      it "re-renders the 'new' template" do
        post :create, {:internal_message => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested internal_message" do
        internal_message = InternalMessage.create! valid_attributes
        put :update, {:id => internal_message.to_param, :internal_message => new_attributes}, valid_session
        internal_message.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested internal_message as @internal_message" do
        internal_message = InternalMessage.create! valid_attributes
        put :update, {:id => internal_message.to_param, :internal_message => valid_attributes}, valid_session
        expect(assigns(:internal_message)).to eq(internal_message)
      end

      it "redirects to the internal_message" do
        internal_message = InternalMessage.create! valid_attributes
        put :update, {:id => internal_message.to_param, :internal_message => valid_attributes}, valid_session
        expect(response).to redirect_to(internal_message)
      end
    end

    describe "with invalid params" do
      it "assigns the internal_message as @internal_message" do
        internal_message = InternalMessage.create! valid_attributes
        put :update, {:id => internal_message.to_param, :internal_message => invalid_attributes}, valid_session
        expect(assigns(:internal_message)).to eq(internal_message)
      end

      it "re-renders the 'edit' template" do
        internal_message = InternalMessage.create! valid_attributes
        put :update, {:id => internal_message.to_param, :internal_message => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested internal_message" do
      internal_message = InternalMessage.create! valid_attributes
      expect {
        delete :destroy, {:id => internal_message.to_param}, valid_session
      }.to change(InternalMessage, :count).by(-1)
    end

    it "redirects to the internal_messages list" do
      internal_message = InternalMessage.create! valid_attributes
      delete :destroy, {:id => internal_message.to_param}, valid_session
      expect(response).to redirect_to(internal_messages_url)
    end
  end

end
